/*
 * PepperReader
 * Fintan Docker integration experiment; TODO: update to openapi: 3.0.0, also cf. https://swagger.io/docs/specification/2-0/file-upload/
 *
 * OpenAPI spec version: 1.0.0
 * Contact: christian.chiarcos@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.acoli.fintan.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
