/*
 * PepperReader
 * Fintan Docker integration experiment; TODO: update to openapi: 3.0.0, also cf. https://swagger.io/docs/specification/2-0/file-upload/
 *
 * OpenAPI spec version: 1.0.0
 * Contact: christian.chiarcos@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import java.io.File;

import org.junit.Test;
import org.acoli.fintan.swagger.client.api.CorpusApi;
import org.acoli.fintan.swagger.client.model.Response;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CorpusApi
 */
@Ignore
public class CorpusApiTest {

    private final CorpusApi api = new CorpusApi();

    
    /**
     * Send raw data
     *
     * resource/data ID
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addDataTest() throws Exception {
        String id = null;
        String importer = null;
        String format = null;
        String blob = null;
        Response response = api.addData(id, importer, format, blob);

        // TODO: test validations
    }
    
    /**
     * Upload a corpus file
     *
     * path to a local file
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addFileTest() throws Exception {
        String id = null;
        String importer = null;
        String format = null;
        File file = null;
        Response response = api.addFile(id, importer, format, file);

        // TODO: test validations
    }
    
    /**
     * Deletes a resource
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteTest() throws Exception {
        String id = null;
        api.delete(id);

        // TODO: test validations
    }
    
    /**
     * Get processed data (full or partial)
     *
     * result (full or partial)
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getResponseTest() throws Exception {
        String id = null;
        Response response = api.getResponse(id);

        // TODO: test validations
    }
    
}
